src/Entity/Motif.php
<?php

namespace App\Entity;

use App\Repository\MotifRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MotifRepository::class)]
class Motif
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $motif_influencer = null;

    #[ORM\Column(length: 255)]
    private ?string $motif_company = null;

    #[ORM\OneToMany(mappedBy: 'motif', targetEntity: ContactInfluencer::class)]
    private Collection $contactInfluencers;

    #[ORM\OneToMany(mappedBy: 'motif', targetEntity: ContactCompany::class)]
    private Collection $contactCompanies;

    public function __construct()
    {
        $this->contactInfluencers = new ArrayCollection();
        $this->contactCompanies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMotifInfluencer(): ?string
    {
        return $this->motif_influencer;
    }

    public function setMotifInfluencer(string $motif_influencer): static
    {
        $this->motif_influencer = $motif_influencer;

        return $this;
    }

    public function getMotifCompany(): ?string
    {
        return $this->motif_company;
    }

    public function setMotifCompany(string $motif_company): static
    {
        $this->motif_company = $motif_company;

        return $this;
    }

    /**
     * @return Collection<int, ContactInfluencer>
     */
    public function getContactInfluencers(): Collection
    {
        return $this->contactInfluencers;
    }

    public function addContactInfluencer(ContactInfluencer $contactInfluencer): static
    {
        if (!$this->contactInfluencers->contains($contactInfluencer)) {
            $this->contactInfluencers->add($contactInfluencer);
            $contactInfluencer->setMotif($this);
        }

        return $this;
    }

    public function removeContactInfluencer(ContactInfluencer $contactInfluencer): static
    {
        if ($this->contactInfluencers->removeElement($contactInfluencer)) {
            // set the owning side to null (unless already changed)
            if ($contactInfluencer->getMotif() === $this) {
                $contactInfluencer->setMotif(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ContactCompany>
     */
    public function getContactCompanies(): Collection
    {
        return $this->contactCompanies;
    }

    public function addContactCompany(ContactCompany $contactCompany): static
    {
        if (!$this->contactCompanies->contains($contactCompany)) {
            $this->contactCompanies->add($contactCompany);
            $contactCompany->setMotif($this);
        }

        return $this;
    }

    public function removeContactCompany(ContactCompany $contactCompany): static
    {
        if ($this->contactCompanies->removeElement($contactCompany)) {
            // set the owning side to null (unless already changed)
            if ($contactCompany->getMotif() === $this) {
                $contactCompany->setMotif(null);
            }
        }

        return $this;
    }
}

templates/ceo/company/company.html.twig
{% extends "base.html.twig" %}
{% block title %}Demande Concernant Les Entreprises
{% endblock %}

{% block body %}
    {{ render(controller('App\\Controller\\Admin\\AdminCeoController::navbar')) }}
    <div class="container mt-4 ">
        {% if company is not empty %}
            <div class="row company-ceo">
                {% for comp in company %}
                    {% if comp.isDisplayed %}
                        {% set endDate = comp.end ? comp.end|date('U') : null %}
                        {% set oneWeekBeforeEnd = endDate ? endDate - (7 * 24 * 60 * 60) : null %}
                        {% set now = 'now'|date('U') %}
                        {% set isWarningPeriod = oneWeekBeforeEnd and now > oneWeekBeforeEnd %}
                        <div class="col-md-4 mb-4">
                            <div class="card h-100 shadow-sm {{ isWarningPeriod ? 'bg-danger text-white' : '' }} position-relative">
                                <div class="card-header d-flex justify-content-between align-items-center">
                                    <h5 class="my-0">{{ comp.company }}</h5>

                                    {% if comp.userImage %}
                                        <img src="{{ asset('assets/uploads/' ~ comp.userImage) }}"
                                             style="width: 40px; height: 40px;" class="rounded-circle img-fluid"
                                             data-bs-toggle="tooltip"
                                             data-bs-title="{{ comp.firstname }} {{ comp.lastname }}">
                                    {% else %}
                                        Pas d'image
                                    {% endif %}


                                    {% if comp.notificationIsNew and not comp.notificationIsSeen %}
                                        <span class="badge bg-danger text-white position-absolute"
                                              style="top: -10px; right: -10px;">Nouveau</span>
                                    {% endif %}
                                </div>
                                <div class="card-body">
                                    <p class="card-text">
                                        <strong>Email :</strong>
                                        {{ comp.email }}</p>
                                    <p class="card-text">
                                        <strong>Motif :</strong>
                                        {{ comp.motif }}</p>
                                    <p class="card-text">
                                        {% if comp.start == null and comp.end == null %}
                                    <p>Pas de dates définies pour le moment</p>
                                    {% else %}
                                        <strong>Dates proposées :</strong>
                                        {{ comp.start ? comp.start|date('d-m-Y') : '' }}
                                        -
                                        {{ comp.end ? comp.end|date('d-m-Y') : '' }}</p>
                                    {% endif %}
                                </div>
                                <div class="card-footer">
                                    <a href="{{ path('ceo_company_show', {'id': comp.id}) }}"
                                       class="btn btn-primary btn-sm">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                             fill="currentColor" class="bi bi-eye-fill" viewbox="0 0 16 16">
                                            <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0"/>
                                            <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7"/>
                                        </svg>
                                        Voir</a>
                                    <a href="{{ path('ceo_company_delete', {'id': comp.id}) }}"
                                       class="btn btn-danger btn-sm">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                             fill="currentColor" class="bi bi-trash-fill" viewbox="0 0 16 16">
                                            <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0"/>
                                        </svg>
                                        Supprimer</a>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% else %}
                    <div class="col">
                        <p class="text-center">Il n'y a pas de demande.</p>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p class="text-center">Il n'y a pas de demande.</p>
        {% endif %}
    </div>
{% endblock %}
{% block javascript %}
<script>
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>
{% endblock %}

templates/ceo/company/show.html.twig
{% extends "base.html.twig" %}

{% block title %}Candidature{% endblock %}

{% block body %}
	{{ render(controller('App\\Controller\\Admin\\AdminCeoController::navbar')) }}<body class="detail-company">
	<div class="container mt-4">
		<div class="row">
			<div class="col-md-6">
				<div class="card mb-4">
					<div class="card-header">
						<h2 class="card-title ">{{ company.email }}</h2>
					</div>
					<div class="card-body">
						<p><strong>Motif:</strong> {{ company.motif.motifCompany }}</p>
						<p><strong>Dates:</strong>
							{{ company.start ? company.start|date('d-m-Y') : '' }}
							-
							{{ company.end ? company.end|date('d-m-Y') : '' }}
						</p>
						<p><strong>Contact:</strong> {{ company.firstname }} {{ company.lastname }}</p>
						<pre><strong>Texte:</strong> {{ company.text }}</pre>
					</div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="card mb-4">
					<div class="card-body">
						{{ form_start(form) }}
						<div class="form-group">
							{{ form_label(form.title, 'Titre du partenariat') }}
							{{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
							{{ form_errors(form.title) }}
						</div>
						<h3>Sélectionnez des dates</h3>
						<div class="form-group">
							{{ form_label(form.start, 'Date de début') }}
							{{ form_widget(form.start, {'attr': {'class': 'form-control'}}) }}
							{{ form_errors(form.start) }}
						</div>
						<div class="form-group">
							{{ form_label(form.end, 'Date de fin') }}
							{{ form_widget(form.end, {'attr': {'class': 'form-control'}}) }}
							{{ form_errors(form.end) }}
						</div>
						<div class="form-group">
							{{ form_label(form.description, 'Description du contrat') }}
							{{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
							{{ form_errors(form.description) }}
						</div>
						<div class="form-check">
							{{ form_label(form.all_day, 'Journée entière') }}
							{{ form_widget(form.all_day, {'attr': {'class': 'form-check-input'}}) }}
							{{ form_errors(form.all_day) }}
						</div>
						{% if form.user is defined %}
							<div class="form-group mb-3">
								{{ form_label(form.user, 'Selectionnez un utilisateur') }}
								{{ form_widget(form.user, {'attr': {'class': 'form-control'}}) }}
								{{ form_errors(form.user) }}
							</div>
						{% endif %}
						<button type="submit" class="btn btn-success">Choisir l'influenceur</button>
						{{ form_end(form) }}
					</div>
				</div>
				<a href="mailto:{{ company.email }}" target="_blank" class="btn btn-primary btn-block">Répondre par mail</a>
			</div>
		</div>
		</div>
	</div>
</body>
{% endblock %}